name: Android dev CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate keystore.properties
        run: |
          echo "$KEYSTORE_PROPERTIES" | base64 --decode > keystore.properties
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: Create Keystore Directory
        run: mkdir -p androidApp/keystore

      - name: Generate compose-calculator-keystore.jks
        run: |
          echo "$KEYSTORE_RELEASE" | base64 --decode > androidApp/keystore/compose-calculator-keystore.jks
        env:
          KEYSTORE_RELEASE: ${{ secrets.KEYSTORE_RELEASE }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane
        run: gem install fastlane -N --no-document

      - name: Install Dependencies
        run: bundle install

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Fastlane
        run: bundle exec fastlane distribute firebase_cli_token:$FIREBASE_TOKEN
        env:
          KEYSTORE_RELEASE: ${{ secrets.FIREBASE_TOKEN }}
