name: Android dev CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane
        run: gem install fastlane -N --no-document

      - name: Install Dependencies
        run: bundle install

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Fastlane
        run: bundle exec fastlane distribution
